### ISSUE TITLE
slalpha3 - Not honoring different distrubution

### ISSUE THREAD

**Issue by jimk-osu** [ballerina-platform/ballerina-update-tool#143]
**Description:**
Using Ballerina Swan Lake Alpha 3, I am unable to use a different distribution `bal dist use 1.2.6`.

Example of a 1.2.6 based project that has been in production for while when trying to run with Alpha 3:

```
ERROR [main.bal:(2:1,2:25)] cannot resolve module 'ballerina/config'
ERROR [main.bal:(4:1,4:29)] cannot resolve module 'ballerina/kubernetes'
ERROR [main.bal:(6:1,6:30)] cannot resolve module 'ballerina/stringutils'
ERROR [main.bal:(38:28,40:3)] incompatible types: expected 'ballerina/http:1.1.0-alpha5:Client', found '(ballerina/http:1.1.0-alpha5:Client|ballerina/http:1.1.0-alpha5:ClientError)'
ERROR [main.bal:(39:5,39:20)] undefined field 'timeoutInMillis' in record 'ballerina/http:1.1.0-alpha5:ClientConfiguration'
ERROR [main.bal:(39:22,39:51)] undefined function 'getAsInt'
ERROR [main.bal:(39:22,39:51)] undefined module 'config'
ERROR [main.bal:(54:24,54:58)] incompatible types: expected 'ballerina/http:1.1.0-alpha5:Client', found '(ballerina/http:1.1.0-alpha5:Client|ballerina/http:1.1.0-alpha5:ClientError)'
ERROR [main.bal:(54:28,54:57)] undefined function 'getAsString'
ERROR [main.bal:(54:28,54:57)] undefined module 'config'
ERROR [main.bal:(56:1,58:2)] undefined annotation 'Service'
ERROR [main.bal:(56:1,58:2)] undefined module 'kubernetes'
ERROR [main.bal:(62:1,72:2)] undefined annotation 'Deployment'
ERROR [main.bal:(62:1,72:2)] undefined module 'kubernetes'
ERROR [main.bal:(73:1,75:2)] undefined annotation 'ConfigMap'
ERROR [main.bal:(73:1,75:2)] undefined module 'kubernetes'
ERROR [main.bal:(77:5,77:13)] undefined field 'basePath' in record 'ballerina/http:1.1.0-alpha5:HttpServiceConfig'
ERROR [main.bal:(80:9,80:15)] unknown type 'person'
ERROR [main.bal:(82:9,82:16)] undefined field 'methods' in record 'ballerina/http:1.1.0-alpha5:HttpResourceConfig'
ERROR [main.bal:(83:9,83:13)] undefined field 'path' in record 'ballerina/http:1.1.0-alpha5:HttpResourceConfig'
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
```
Ballerina Swan Lake Alpha 3
Language specification v2020-12-17
Update Tool 1.3.1
```

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Install [deb](https://dist.ballerina.io/downloads/swan-lake-alpha3/ballerina-linux-installer-x64-swan-lake-alpha3.deb)
2. `bal dist pull 1.2.6`
3. `bal dist use 1.2.6`
4. Run existing 1.2.6 based project

**Related Issues:**

**Comment by suganyasuven** [comment]
Which ubuntu version you are using? Could you please share the output you get for `sudo bal -v`?

**Comment by jimk-osu** [comment]
Its running on a `debian:jessie` pod within a kubernetes cluster (an admin/quick test pod).

I just checked and `~/.ballerina/ballerina-version` does not exist:

```shell
ls  ~/.ballerina/
Settings.toml  repositories
```

**Comment by suganyasuven** [comment]
> Its running on a `debian:jessie` pod within a kubernetes cluster (an admin/quick test pod).
> 
> I just checked and `~/.ballerina/ballerina-version` does not exist:
> 
> ```shell
> ls  ~/.ballerina/
> Settings.toml  repositories
> ```

Could you please share the output you get for `sudo bal -v` as well?

**Comment by jimk-osu** [comment]
The pod is running as root and there is no out-of-the-box in `debian:jessie` (not best practice to run a root level pod, I know 😄 )

**Comment by jimk-osu** [comment]
For what its worth I also tried this using `ballerina/ballerina:latest`:

```shell
bash-5.0$ bal -v
Ballerina Swan Lake Alpha 4
Language specification v2020-12-17
Update Tool 1.3.1

bash-5.0$ bal dist pull 1.2.6
Fetching the '1.2.6' distribution from the remote server...
Downloading 1.2.6 100% [===========================================================] 110/110 MB (0:00:03 / 0:00:00)

Fetching the dependencies for '1.2.6' from the remote server...
Downloading jdk8u202-b08-jre 100% [==================================================] 39/39 MB (0:00:00 / 0:00:00)
'1.2.6' successfully set as the active distribution

bash-5.0$ bal dist list
/ballerina/runtime/bin/bal: line 54: /ballerina/runtime/bin/../dependencies/jdk8u202-b08-jre/bin/java: No such file or directory

bash-5.0$ bal -v
Error: Ballerina is supported only on JDK 1.8
/ballerina/runtime/bin/bal: line 105: /ballerina/runtime/bin/../dependencies/jdk8u202-b08-jre/bin/java: No such file or directory

bash-5.0$ bal dist use 1.2.6
/ballerina/runtime/bin/bal: line 54: /ballerina/runtime/bin/../dependencies/jdk8u202-b08-jre/bin/java: No such file or directory

bash-5.0$ ls /ballerina/runtime/dependencies/jdk8u202-b08-jre/bin/java
/ballerina/runtime/dependencies/jdk8u202-b08-jre/bin/java

bash-5.0$ ls -lah /ballerina/runtime/dependencies/jdk8u202-b08-jre/bin/java
-rwxrwxrwx    1 ballerin troupe      8.5K Apr 21 15:31 /ballerina/runtime/dependencies/jdk8u202-b08-jre/bin/java

bash-5.0$ id
uid=100(ballerina) gid=1000(troupe) groups=1000(troupe)

```

**Comment by suganyasuven** [comment]
> For what its worth I also tried this using `ballerina/ballerina:latest`:
> 
> ```shell
> bash-5.0$ bal -v
> Ballerina Swan Lake Alpha 4
> Language specification v2020-12-17
> Update Tool 1.3.1
> 
> bash-5.0$ bal dist pull 1.2.6
> Fetching the '1.2.6' distribution from the remote server...
> Downloading 1.2.6 100% [===========================================================] 110/110 MB (0:00:03 / 0:00:00)
> 
> Fetching the dependencies for '1.2.6' from the remote server...
> Downloading jdk8u202-b08-jre 100% [==================================================] 39/39 MB (0:00:00 / 0:00:00)
> '1.2.6' successfully set as the active distribution
> 
> bash-5.0$ bal dist list
> /ballerina/runtime/bin/bal: line 54: /ballerina/runtime/bin/../dependencies/jdk8u202-b08-jre/bin/java: No such file or directory
> 
> bash-5.0$ bal -v
> Error: Ballerina is supported only on JDK 1.8
> /ballerina/runtime/bin/bal: line 105: /ballerina/runtime/bin/../dependencies/jdk8u202-b08-jre/bin/java: No such file or directory
> 
> bash-5.0$ bal dist use 1.2.6
> /ballerina/runtime/bin/bal: line 54: /ballerina/runtime/bin/../dependencies/jdk8u202-b08-jre/bin/java: No such file or directory
> 
> bash-5.0$ ls /ballerina/runtime/dependencies/jdk8u202-b08-jre/bin/java
> /ballerina/runtime/dependencies/jdk8u202-b08-jre/bin/java
> 
> bash-5.0$ ls -lah /ballerina/runtime/dependencies/jdk8u202-b08-jre/bin/java
> -rwxrwxrwx    1 ballerin troupe      8.5K Apr 21 15:31 /ballerina/runtime/dependencies/jdk8u202-b08-jre/bin/java
> 
> bash-5.0$ id
> uid=100(ballerina) gid=1000(troupe) groups=1000(troupe)
> ```

Seems the file is there and it has permissions as well.

**Comment by suganyasuven** [comment]
Is there any specific use case for switching distribution within a pod? If you want only 1.2.6, then you can try using `ballerina/ballerina:1.2.6`.

**Comment by keizer619** [comment]
@jimk-osu 
Thank you reporting this. We have review packing update tool in docker image and since there are issues in the environment and make it simple, we have decided to remove update tool functionality from ballerina image. Therefore now we cannot use ballerina update tool commands in docker and we need to use docker ballerina image versions in order to switch in between.

I will be closing the issue, please feel free to reopen if there are any concerns
