### ISSUE TITLE
In beta RC4, Beta2 version is not shown when I list the available versions

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-update-tool#169]
I used the command` bal dist list`.
Beta2 is not shown, But using `bal dist use slbeta2` I can successfully switch to beta2.

![image](https://user-images.githubusercontent.com/9362271/123605694-bb1db380-d819-11eb-9003-455d64141f77.png)

Affected version: Swan lake Beta RC4

**Comment by suganyasuven** [comment]
This is expected behavior as Swan lake Beta RC4 is not published.
