### ISSUE TITLE
`bal update` and `bal dist pull ....` commands require root access

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-update-tool#185]
**Description:**
$subject.
```
bal -v // works

bal update // gives permission denied.
sudo bal update // works

bal dist pull slbeta5 // gives permission denied.
sudo bal dist pull slbeta5 // works
```
Please refer to the below screenshot. 
![Screenshot from 2021-12-08 10-40-54](https://user-images.githubusercontent.com/39232462/145151921-37bc37fe-d3e3-4aa1-aaad-e9a8fb0182c1.png)

**OS, DB, other environment details and versions:**
update tool version '1.3.6'
Ubuntu 20.04.3 LTS

**Comment by udda1996** [comment]
@lochana-chathura This is the expected behavior. As the distribution location is not writable, the command should be executed with root privileges.

**Comment by lochana-chathura** [comment]
@udda1996 Ack. Hence closing.
