### ISSUE TITLE
Progress bar shows an incorrect pack size while downloading

### ISSUE THREAD

**Issue by udda1996** [ballerina-platform/ballerina-update-tool#186]
**Description:**
While downloading a new distribution using 'bal dist pull <version>', it shows an incorrect pack size in the progress bar. 

<img width="787" alt="Screenshot 2021-12-15 at 09 53 52" src="https://user-images.githubusercontent.com/66210480/146123632-11b7ca84-7c86-4ae1-be88-5404ce816c52.png">

<img width="764" alt="Screenshot 2021-12-15 at 09 56 24" src="https://user-images.githubusercontent.com/66210480/146123684-3043a9b1-89e1-4a6a-8886-573ddb393cc3.png">

**Comment by Miranlfk** [comment]
This issue is not reproducible 

![test1](https://user-images.githubusercontent.com/85722530/191190095-ab75be37-259c-4dda-aaa5-202b5331d250.png)
![tes2](https://user-images.githubusercontent.com/85722530/191190204-a47d87f0-d440-4f48-be07-6398ae24c235.png)
