### ISSUE TITLE
bal -v -h command does not open the help window

### ISSUE THREAD

**Issue by NipunaMadhushan** [ballerina-platform/ballerina-update-tool#199]
Label - Less Priority

**Description:**
When we run the `bal -v -h` command on any operating system, it will simply returns the ballerina version. 

```
Ballerina Swan Lake Beta 6
Language specification 2021R1
Update Tool 1.3.7-rc1
```

However when we run the `ballerina version -h` command, it returns help window.

**Steps to reproduce:**
Run the following command on any operating system.
`bal -v -h`

**Affected Versions:**
All the versions

**Comment by keizer619** [comment]
I think we should show version for `ballerina version -h` as well

**Comment by Cioraz** [comment]
Hey i can assist in this issue

**Comment by deepakchethan** [comment]
Hi @keizer619, I'd like to work on this

**Comment by udda1996** [comment]
👋 Welcome, @deepakchethan ! 🚀

We're thrilled to have you join the Ballerina Lang community! Whether you're a seasoned developer or just starting your journey with Ballerina, we value your contributions and look forward to collaborating with you.
To help you get started, here are some essential resources:

   i.  Understanding Ballerina Platform:
    Learn what Ballerina is all about: [Ballerina Platform](https://github.com/ballerina-platform/ballerina-release/blob/master/CONTRIBUTING.md)
    ii. How to Contribute:
    Read our contributing guidelines to understand how you can contribute effectively: [Contribution Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
    iii. Contributing to the Ballerina library:
    If you're interested in contributing to our library, here are the guidelines: [Library Contribution Guide](https://github.com/ballerina-platform/ballerina-standard-library/blob/main/CONTRIBUTING.md)
    iv. Learn Ballerina:
    If you're new to Ballerina or want to enhance your skills, our official website offers a wealth of learning resources: [Learn Ballerina](https://ballerina.io/learn/)
    v. Get Help and Connect:
    Join our Discord community to chat with fellow Ballerina enthusiasts and get assistance: [Ballerina Discord](https://discord.com/invite/ballerinalang)

Remember, no contribution is too small, and your feedback is invaluable. Feel free to ask questions, propose ideas, or report issues. Together, we can make Ballerina even better!
Happy coding! 🎉

**Comment by udda1996** [comment]
👋 Welcome, @deepakchethan ! 🚀

We're thrilled to have you join the Ballerina Lang community! Whether you're a seasoned developer or just starting your journey with Ballerina, we value your contributions and look forward to collaborating with you.
To help you get started, here are some essential resources:

1. Understanding [Ballerina Platform](https://github.com/ballerina-platform/ballerina-release/blob/master/CONTRIBUTING.md):
Learn what Ballerina is all about: Ballerina Platform
2. How to Contribute:
Read our contributing guidelines to understand how you can contribute effectively: [Contribution Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
3. Contributing to the Ballerina library:
If you're interested in contributing to our library, here are the guidelines: [Library Contribution Guide](https://github.com/ballerina-platform/ballerina-standard-library/blob/main/CONTRIBUTING.md)
4. [Learn Ballerina](https://ballerina.io/learn/):
If you're new to Ballerina or want to enhance your skills, our official website offers a wealth of learning resources: Learn Ballerina
5. Get Help and Connect:
Join our Discord community to chat with fellow Ballerina enthusiasts and get assistance: [Ballerina Discord](https://discord.com/invite/ballerinalang)

Remember, no contribution is too small, and your feedback is invaluable. Feel free to ask questions, propose ideas, or report issues. Together, we can make Ballerina even better!
Happy coding! 🎉

**Comment by udda1996** [comment]
@deepakchethan please feel free to raise any issue you come across related to Ballerina update flow and testing the fixes.

**Comment by priyavratamohan** [comment]
Hi, I'd like to work on this issue

**Comment by keizer619** [comment]
@deepakchethan if you are not working on this please let us know, we can assign this to @priyavratamohan

**Comment by neelshah2409** [comment]
@keizer619 Even I would like to work on it

**Comment by keizer619** [comment]
@neelshah2409 If you can send a PR we can include

**Comment by DanKibwikaAkillix** [comment]
Helle everyone , is the issue fixed already ? i'd like to work on it

**Comment by keizer619** [comment]
> Helle everyone , is the issue fixed already ? i'd like to work on it

Hi @DanKibwikaAkillix 
This is not fixed and you can start working.

**Comment by Jaagrav** [comment]
@keizer619 PTAL at this PR #369

**Comment by NipunaMadhushan** [comment]
@Jaagrav We have discussed about this issue internally and decided to show only the version info for any command below.
`bal version -h`
`bal --version -h`
`bal -v -h`
`bal version --help`
`bal --version --help`
`bal -v --help`

We made this decision as it has been the norm in most of other languages.
