### ISSUE TITLE
Ballerina dist update do not update to the latest

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-update-tool#20]
**Description:**
When I do a dist update when using jballerina-1.1.4 the ballerina version will be set to jballerina-1.1.1 which is an older version.

Fetching the latest patch distribution for 'jballerina-1.1.4' from the remote server...
Successfully set the latest patch distribution 'jballerina-1.1.1' as the active distribution

**Comment by parkavi11** [comment]
This issue is fixed with update-tool version 0.8.5

**Comment by keizer619** [comment]
This is fixed by reverting centos fix
https://github.com/ballerina-platform/ballerina-update-tool/pull/22
