### ISSUE TITLE
`bal version` command returned a Permission denied error

### ISSUE THREAD

**Issue by nilushancosta** [ballerina-platform/ballerina-update-tool#214]
**Description:**
`bal version` command returned a permission denied error. I had to change the File permissions manually to get it to work. 

**Steps to reproduce:**
After changing the active Ballerina distribution to `2201.0.0`, I executed a `bal version` command. However I got a Permission denied error.
<img width="1160" alt="Screenshot 2022-02-03 at 15 28 12" src="https://user-images.githubusercontent.com/19643850/152323028-63719256-d4bb-45b3-b928-74e6b7bf5430.png">

It was only after I changed the file permissions using `chmod` I was able to get the command to work
<img width="1280" alt="Screenshot 2022-02-03 at 15 41 11" src="https://user-images.githubusercontent.com/19643850/152322551-1e43f5a8-1ab5-49e0-b680-c7dab51fb5ba.png">

**Affected Versions:**
Swan lake

**OS, DB, other environment details and versions:**
MacOS Big Sur 11.4

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by udda1996** [comment]
Closing as this is not reproducible.
