### ISSUE TITLE
Current version (not published) is not showing as installed in `bal dist list`

### ISSUE THREAD

**Issue by NipunaMadhushan** [ballerina-platform/ballerina-update-tool#217]
**Description:**
When we are having different dsitribution versions (e.g: 2201.0.1-SNAPSHOT), the `bal dist list` command is not showing the installed version as it has been installed. Reason is that the current version has not been published yet.

<img width="834" alt="Screenshot 2022-02-10 at 14 57 56" src="https://user-images.githubusercontent.com/51471998/153378906-3fa0db98-f7fe-43fd-8ea7-26d5658370d8.png">

**Steps to reproduce:**
Download the installer (ubuntu deb/rpm, macos pkg, windows msi) from the daily build in ballerina-distribution or build the ballerina-distribution and generate installer from the pack.
Install ballerina from the installer and run the `bal dist list`.

**Affected Versions:**
All the versions

**OS, DB, other environment details and versions:**
All the Operating systems.

**Comment by udda1996** [comment]
We can not pull a non-published distribution using `bal dist pull`. But still you can switch to any locally available distribution using `bal dist use <distribution_name>`
