### ISSUE TITLE
Installing Ballerina with Ubuntu Software Store isn't working as expected

### ISSUE THREAD

**Issue by ragwap** [ballerina-platform/ballerina-update-tool#225]
**Description:**
I'm trying to download and install ballerina-2201.0.2-swan-lake-linux-x64.deb for the first time in my Ubuntu environment with Ubuntu Software Store. 

**Steps to reproduce:**

Given below are the steps I followed and the error I came across:

1. Downloaded the aforementioned .deb file from https://ballerina.io/downloads/
2. Once the file was downloaded, I double clicked and it opened in Ubuntu Software Store.
3. Clicked on the "Install" button.
4. The following error seen in the attached screenshot was prompted:

![Screenshot from 2022-03-29 10-06-33](https://user-images.githubusercontent.com/27797008/160553436-c3ac9df6-0c0c-4e7e-8ac5-2875edcfe8a0.png)

Then I execute the dpkg command mentioned in the error response. Yet the issue persisted.

**Affected Versions:**

**OS, DB, other environment details and versions:**

OS: Ubuntu 20.04.2 LTS

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lochana-chathura** [comment]
I had the same experience when double click and install through the store. 
As this is the most likely case one would try when installing ballerina for the first time, we need to fix this.

**Comment by NipunaMadhushan** [comment]
@ragwap seems like the same issue in https://github.com/ballerina-platform/ballerina-distribution/issues/2736. But the issue I mentioned happened only when we had installed another version beforehand. Can you double check this again whether it is still happening when you try to install deb package for the first time? 
When you already installed another version, you can use terminal command `dpkg -i --force-overwrite <deb-package>` as a work around for the issue I mentioned above.
