### ISSUE TITLE
Update tools does not pull distributions

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-update-tool#226]
**Description:**
When I tried to pull a distribution it says the particular distribution is not found.
![image](https://user-images.githubusercontent.com/35211477/174241248-1840ea1f-9bf0-4a9b-81a3-bfd1d508531c.png)

However when I tried the `bal dist list` command the distribution gets listed there.
![image](https://user-images.githubusercontent.com/35211477/174240288-d788222a-a672-4903-a91a-c9fd6aa79872.png)

**Steps to reproduce:**
try `bal dist pull 2201.0.4`
**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by suganyasuven** [comment]
This is because of the ballerina central api changes. We have reverted it back. We ll look in to it.

**Comment by malinthar** [comment]
@suganyasuven The stage server has the same issue

**Comment by suganyasuven** [comment]
> @suganyasuven The stage server has the same issue

Yes. We have fixed it . Just deployed to the higher environments.

**Comment by malinthar** [comment]
> > @suganyasuven The stage server has the same issue
> 
> Yes. We have fixed it . Just deployed to the higher environments.

Ack. Thanks
