### ISSUE TITLE
Improve local disttribution in dist list

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-update-tool#243]
**Description:**
Currently 1.2.x releases are shown in the top in local and remote lists in `bal dist list`, this will bring down later versions as list get increased. This can be improved by showing latest major versions top. 

<img width="509" alt="Screenshot 2022-10-22 at 16 59 18" src="https://user-images.githubusercontent.com/2918812/197336740-d423d8eb-728c-4286-9371-4d32ca3f68a7.png">

**Comment by udda1996** [comment]
These are the changes done for the output of `bal dist list` command

- Channels are listed from latest to oldest 
- The distributions are listed from latest to oldest
- `... To list all the previous distributions execute 'bal dist list -a'` phrase is removed and added `Use 'bal dist list -a' to list all the distributions under each channel.` line at the bottom of the command output when the `-a` flag is not used

Following will be the new output for `bal dist list`
 
<img width="649" alt="Screenshot 2022-10-28 at 16 57 11" src="https://user-images.githubusercontent.com/66210480/198578410-d7925325-b95c-40f4-88fe-15b70bc437c0.png">
