### ISSUE TITLE
[Bug]: ballerina: distribution '2201.4.1' not found

### ISSUE THREAD

**Issue by gruber123** [ballerina-platform/ballerina-update-tool#278]
### Description

No distribution

# bal dist pull 2201.4.1
Checking for newer versions of the update tool...
ballerina: distribution '2201.4.1' not found

# bal dist list
Distributions available locally:

* 2201.4.0

Distributions available remotely:

Swan Lake channel

* 2201.4.0 - latest
  2201.3.4
  2201.3.3
  2201.3.2
  2201.3.1
  2201.3.0
  2201.2.4
  2201.2.3
  2201.2.2
  2201.2.1

1.* channel

  1.2.37 - latest
  1.2.36
  1.2.35
  1.2.34
  1.2.33
  1.2.32
  1.2.31
  1.2.30
  1.2.29
  1.2.28

### Related area

-> Update Tool

**Comment by udda1996** [comment]
closing since this is fixed
