### ISSUE TITLE
Revisit tool updating during `bal dist pull <version>` / `bal dist update` commands

### ISSUE THREAD

**Issue by udda1996** [ballerina-platform/ballerina-update-tool#288]
**Description:**
Currently `bal dist pull` command is updating the tool if a new version is available. But the changes in the new version won't be seen during the `pull` command execution since it executes the previous version's jar. To fix this we can exit executing `pull` command once there is a new tool version and ask user to update the tool first using `bal update` and then use the `pull` command. This will ensure that the user gets the latest tool to use with `pull` command.

**Comment by udda1996** [comment]
Had a discussion on this with @keizer619 @anupama-pathirage. Concluded to prompt users to update the tool by terminating `bal dist pull` command once there is a tool fix with backward incompatible changes. In case there is a a tool update without backward incompatible changes we just show a message for users mentioning that there is a new tool version. We will add this fix with the next tool release

**Comment by udda1996** [comment]
We can add additional flag at the back-end to mark the backward incompatibility or we can use the semver to check the compatibility from the client side . @keizer619 WDYT?

**Comment by keizer619** [comment]
We have left the existing behaviour to get latest update version with `dist update` and updated cli and website content as per that
