### ISSUE TITLE
Remove access denied error in update tool commands

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-update-tool#291]
**Description:**
An access denied error gets displayed in the CLI logs, when certain parameters are not recognized in the issues update tool commands as shown in the examples below. Need to correct this and display the correct error messages.

**Example 1**
<img width="757" alt="Screenshot 2023-04-21 at 09 32 29" src="https://user-images.githubusercontent.com/11707273/233700904-858458e0-ef27-412b-8205-923ff3392fc6.png">

**Example 2**
<img width="754" alt="Screenshot 2023-04-21 at 09 33 18" src="https://user-images.githubusercontent.com/11707273/233700913-13afce9c-9519-47ec-8b8b-9bdad66a05c1.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by udda1996** [comment]
Here we check for the permission of installation directory in first place before validating the requested distribution. If the permission is granted we try to download the distribution and give a `distribution not found error` in case of an invalid distribution. If we consider this as a bug, to fix this we can validate the distribution first and then go for the permission check. 

Then for `bal dist pull foo` it will give a `distribution not found` exception without giving `permission denied` message
