### ISSUE TITLE
Bal new command not working for few project-names

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-update-tool#301]
**Description:**
$subject

**Steps to reproduce:**
```
bal new dist
bal new update
```

**Affected Versions:**
2201.5.0

**Comment by HeetVekariya** [comment]
@keizer619 @MohamedSabthar I would like to work on this issue as it is good first issue, can you please elaborate on what exact changes i have to do, so it will be easy for me to make.

**Comment by HeetVekariya** [comment]
@keizer619 can you please explain me the issue, such that i can start work on it.

**Comment by HeetVekariya** [comment]
@keizer619 i am not clear about the issue, so i haven't started working on it.

**Comment by HeetVekariya** [comment]
- @LakshanWeerasinghe @keizer619 what i understand the issue as, we don't have to allow the user to have directory names "dist" and "update"

- Current ```_bal.sh```
```
new)
        _arguments \
            '1: :(-t --template)' \
            '*:: :->templates'
        ;;
```


- Changes which will not allow directory names ```dist``` & ```update```
```
new)
    _arguments \
        '1: :(-t --template)' \
        '2: :_files -W * -/' \
        - '2: :(dist update)'
    ;;
```

- Is it correct ?

**Comment by LakshanWeerasinghe** [comment]
In here when we try to execute one of these commands it will prints an error saying `Unmatched argument at index 0: 'new'`. There are two things we can do this for this issue.

1. Make the `bal new` command to work properly for these types for project names.
2. Give a proper error message to the user so that the user won't get confused.

@azinneera @Dilhasha what approach we should follow?

**Comment by HeetVekariya** [comment]
- @LakshanWeerasinghe let me know the option, whenever finalised, with which we are going to proceed.
- I will work accordingly.

**Comment by udda1996** [comment]
@HeetVekariya we should allow users to create projects with names like with keywords like `update` , `dist`. Currently this is fixed for `update` keywords and `bal new update` is working fine. you can refer to below PR to have an idea on this fix https://github.com/ballerina-platform/ballerina-update-tool/pull/312 . 

Hope you can start work on this issue with the given instructions. Feel free to raise any issue you come across while working on this.

**Comment by HeetVekariya** [comment]
i might not able to work on this issue, so can you please assign this issue to others
