### ISSUE TITLE
Calling `bal tool update` gets picked up as `bal update` in from the update tool

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-update-tool#310]
**Description:**
In U8, for bal tool, a subcommand `update` is introduced. However, the update tool picks up the argument `update` and identifies it as `bal update` and logs error `Unmatched argument at index 0: 'tool'`

**Steps to reproduce:**
With update 8 build pack,
```
% bal tool update
Unmatched argument at index 0: 'tool'
```

**Affected Versions:**
2201.8.0-SNAPSHOT

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
Issue tracking `bal tool` progress - https://github.com/ballerina-platform/ballerina-lang/issues/40264

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by udda1996** [comment]
`bal tool update` is identified as a command similar to `bal dist update` since the `update` sub command is with the same index (index 1). So the command is executed by `bin/bal` instead of `distributions/<distribution>/bin/bal`
