### ISSUE TITLE
Help texts are not consistent for all dist commands

### ISSUE THREAD

**Issue by suganyasuven** [ballerina-platform/ballerina-update-tool#33]
**Description:**
For dist pull,

```
Fetching the '1.2.1' distribution from the remote server...
```

For all other commands,
```
Fetching the latest patch distribution for 'jballerina-1.2.0' from the remote server...
Fetching the 'jballerina-1.2.4' distribution from the remote server...
```

**Suggested Labels:**
Type/Improvement

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by keizer619** [comment]
Fix in following PR
https://github.com/ballerina-platform/ballerina-update-tool/pull/35
