### ISSUE TITLE
Improve dependency directory permission checking

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-update-tool#52]
**Description:**
Usually Ballerina installation directory does not have write permissions. This will be checked in pull and update commands and complain users initially. 

There are some scenarios like following homebrew installation where it has write permissions for installation directory but does not have write permissions for dependency directory. Update tool complains when trying to extract after downloading dependency. It should check and complain initially before downloading anything for better UX.

```
% ballerina dist pull slp8

Fetching the 'slp8' distribution from the remote server...
Downloading slp8 100% [=================================================] 242/242 MB (0:00:20 / 0:00:00)

Fetching the dependencies for 'slp8' from the remote server...
Downloading jdk-11.0.8+10-jre 100% [======================================] 41/41 MB (0:00:04 / 0:00:00)
ballerina: permission denied: you do not have write access to '/usr/local/Cellar/ballerina/1.1.3/libexec/dependencies/jdk-11.0.8+10-jre'
```

**Comment by suganyasuven** [comment]
This bug could not be reproduced. Hence parked it for now.
