### ISSUE TITLE
After the installation version is not updated for the first time

### ISSUE THREAD

**Issue by suganyasuven** [ballerina-platform/ballerina-update-tool#65]
**Description:**
$title
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by suganyasuven** [comment]
This is due to when we issue the `bal -v`,  ballerina version and language-specific version are printed from the ballerina-lang first, and then update tool version is printed from the update tool. But when getting the BALLERINA_HOME we use the `.ballerina/ballerina-version` file. However ballerina version updation logic is inside the update tool. So for the first time, it is not updated. So it picks the already installed version as the default version for the first time.

Suggestions: 
1. We could update the `ballerina-version` during the post-installation. However,  permission issues needs to be considered as the installation will be performed by the root user. Then we don't need the installer version file as well.
2. We could move the logic of the checks of the installer version should be moved to the lang repo.

**Comment by hevayo** [comment]
As the third case shall we inform the user to remove the existing version before installing the new one ? Also we can suggest user to do `bal dist updated` instead.

**Comment by suganyasuven** [comment]
> As the third case shall we inform the user to remove the existing version before installing the new one ? Also we can suggest user to do `bal dist updated` instead.

Yes, we can ask the user to do so. Then we can remove the installer version file as well.

**Comment by keizer619** [comment]
This issue is fixed with this https://github.com/ballerina-platform/ballerina-update-tool/issues/60
