### ISSUE TITLE
`ballerina` file is not removed during the installation of `slalpha` in Windows

### ISSUE THREAD

**Issue by suganyasuven** [ballerina-platform/ballerina-update-tool#72]
**Description:**
$title

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**   
Windows 

**Steps to reproduce:**

**Related Issues:**

**Comment by NipunaMadhushan** [comment]
I checked different scenarios for the above issue. Alpha and Beta versions have `bal.bat` file and Preview versions have `ballerina.bat` file.

When we install a newer version ( alpha / beta versions) from the msi installer and install a preview version from the update tool, there is only `bal.bat` file in the `bin` folder.

When we install a older version (preview version) from the msi installer and install a newer version from the update tool, there is only the `ballerina.bat` file in the `bin` folder. After that we can run `bal update` command and there will only the `bal.bat` file in the `bin` folder.

But when we install a older version and a newer version from msi installers, `bin` contains both `ballerina.bat` and `bal.bat` files. However only the `bal` command works and the `ballerina` command won't work.

![Screenshot (38)](https://user-images.githubusercontent.com/51471998/145988182-049ebe73-ba0f-4a18-b754-28eb7b89d74d.png)

**Comment by keizer619** [comment]
Since post GA versions are having only `bal` file this not required to fix. Hence this issue will be closed and feel free to reopen if there are any concerns
