### ISSUE TITLE
Test Automation

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-update-tool#80]
**Description:**

- [x] Implement integration tests in distribution repository for update tool (https://github.com/ballerina-platform/ballerina-distribution/pull/1275)
- [x] Separate installers tests and update tool tests in current installer tests (https://github.com/ballerina-platform/ballerina-release/pull/84)
- [x]  Installers tests should be executed when installers been generated
- [x] Update tool tests should be executed when new update tool version is released
- [x] Update `ballerina` to `bal` command change in current installer tests
- [x] Enable Macos tests in current installers as Github Actions support Macos  
- [x] Enable Windows tests by resolving windows
     - [x] Make sure tests are running in local windows machine
     - [ ] Check whether possible to fix Github Action permission issue

**Comment by suganyasuven** [comment]
https://github.com/ballerina-platform/ballerina-release/issues/72
